=== glitched-smp/glitchedsmp.fun/public/config.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://glitchedsmp.fun",
  "title": "Glitched SMP Website Config",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "page_title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "public_links": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    },
    "about_us": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "min_rating": {
      "type": "integer"
    },
    "max_rating": {
      "type": "integer"
    },
    "ratings": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "by": {
            "type": "string"
          },
          "rating": {
            "type": "integer"
          },
          "message": {
            "type": "string"
          }
        },
        "required": [
          "by",
          "rating"
        ]
      }
    },
    "updates": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "patchnote",
              "update"
            ]
          },
          "name": {
            "type": "string"
          },
          "added": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "removed": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "changed": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "required": [
          "type",
          "name",
          "added",
          "removed",
          "changed"
        ]
      }
    }
  },
  "required": [
    "page_title",
    "description",
    "public_links",
    "about_us",
    "min_rating",
    "max_rating",
    "ratings",
    "updates"
  ]
}

=== glitched-smp/glitchedsmp.fun/src/config.json
{
  "$schema": "https://glitchedsmp.fun/config.schema.json",
  "page_title": "Glitched SMP",
  "description": "A Unique Minecraft Survival Server.",
  "public_links": {
    "/#home": "Home",
    "/#about": "About Us",
    "/#ratings": "Ratings",
    "/updates.html": "Updates"
  },
  "about_us": [
    "Paragraph #1",
    "Paragraph #2",
    "Paragraph #3",
    "Paragraph #4",
    "Paragraph #5",
    "Paragraph #6",
    "Paragraph #7",
    "Paragraph #8",
    "Paragraph #9",
    "Paragraph #10",
    "Paragraph #11",
    "Paragraph #12",
    "Paragraph #13",
    "Paragraph #14",
    "Paragraph #15",
    "Paragraph #16",
    "Paragraph #17",
    "Paragraph #18",
    "Paragraph #19",
    "Paragraph #20",
    "Duplicate this line (and keep it valid JSON) to add more paragraphs!"
  ],
  "min_rating": 1,
  "max_rating": 10,
  "ratings": [
    {
      "by": "Maxboi152",
      "rating": 9,
      "message": "peak server, other severs I either got bored or touch going on, this one perfect"
    },
    {
      "by": "Plumbasket",
      "rating": 10,
      "message": "This server is the best mc server that ive played yet. it had its downs, but now its pretty fun, your not stuffed with plugins, and like in my old review, very fun and the staff is friendly."
    },
    {
      "by": "Audaciouslord",
      "rating": 1,
      "message": "if i could go beyond i would. server has friendly staff that are generous and dont mind helping you whenever, they always prioritize you and your concerns, members are also friendly ofc some rnt but its fine, server has great lots of exclusive features to add infinite fun and grinding so you never get bored, has great custom stuff that really are impressive. have their own special lore/story area called the mines, insanely grindy but worth it for the best armor ever, good wall to hold the best tools and armor custom created, only downside is its insane OP disables the need for customised setups and stuff, server is somewhat grindy in its exclusivity but thats fitting with me and adds more to the fun and enjoyment, might not be fit everyone but its a nice touch. insanely beautiful generation and builds and custom structures, never regretted joining this."
    },
    {
      "by": "Skid",
      "rating": 9,
      "message": "Nice and vanilla. The staff are friendly and super helpful. First thing we did was play a game together. Simple, peaceful, and a good place to start. Has plenty of useful things to get you going too."
    }
  ],
  "updates": [
    {
      "type": "patchnote",
      "name": "1.8.1.9",
      "added": [
        "This is what was added",
        "Not really, but it should help populate real data later!"
      ],
      "removed": [
        "Removed stuff",
        "None?!?!?!?"
      ],
      "changed": [
        "Meh",
        "I don't wanna!!!"
      ]
    },
    {
      "type": "update",
      "name": "1.5.2",
      "added": [
        "fafawpfawfwajw a fwafwa This is what was added",
        "Not really, but it should hefwa f yiawhfakjwh lp populate real data later!"
      ],
      "removed": [
        "Removed stu fwawfawf ff",
        "None? fawfwa hj!?!?!?"
      ],
      "changed": [
        "Measwfa wh",
        "I don'tf waf afw wanna!!!"
      ]
    }
  ]
}
